### ISSUE TITLE
wrong calculation: precision is not accurate.

### ISSUE THREAD

**Issue by pinggit** [sk1418/HowMuch#10]
```
616054579
11
--
Sum: 6.160546e8
```

should be 616054590
or at least, 6.1605459e8

same even with g:HowMuch_scale set to 20.

**Comment by sk1418** [comment]
@pinggit thank you for using HowMuch and reporting the problem.
Indeed there is a bug in the float number handling when we calculate the sum. I've fixed and pushed in the master branch. Please test again.
