### ISSUE TITLE
Just visualize the sum

### ISSUE THREAD

**Issue by artshcherbina** [sk1418/HowMuch#11]
Hello!

Thank you for the usefull plugin.
Actually, I would like just calculate the sum without modifying the text.

I have modified the HowMuch function like this
    redraw! | echo 'Sum: ' . (type(total)==type("") ? total : HowMuch#float_to_str(total))

Maybe it will be usefull to add this option into plugin.

Best regards,
Artem

**Comment by sk1418** [comment]
@artshcherbina  thanks for the issue.
Are you requesting a new feature? or you want to send a pull request?

**Comment by artshcherbina** [comment]
This is a suggestion for new feature.
