### ISSUE TITLE
Negative exponent return zero

### ISSUE THREAD

**Issue by VolkovIlia** [sk1418/HowMuch#12]
script return:

```
12*10**-4 = 0
```

python return:
```
12*10**-4
0.0012000000000000001
```

**Comment by sk1418** [comment]
@VolkovIlia 
- please check if `py` in your engine list if you calculate using autoCalc
- you may want to set the `g:HowMuch_scale` option (default=2,   `0.0012000` -> `0.00` -> `0`)

**Comment by VolkovIlia** [comment]
result after 

g:HowMuch_scale = 15

```
10**-13 = 1.0e-13
```
but 

```
10-10**-13 = 10
```

**Comment by sk1418** [comment]
@VolkovIlia  Thanks for reporting the issue.
There's a bug in formatting the py calc result. Now it gets fixed:

    scale=15
    10**-13 = 0.0000000000001

    10-10**-13 = 9.999999999999901

Please pull and try again.
