### ISSUE TITLE
python2 is obsolete

### ISSUE THREAD

**Issue by wcazzola** [sk1418/HowMuch#9]
As per a fresh install of vim 8.2 on Fedora 31 this is compiled without the support for python2 because python2 get to end-of-life by the first of January 2020.

As a result your python engine doesn't work anymore.

A easy patch is to change
  - line 302 'python' to 'python3'
  - line 308 'python' to 'python3'
in autoload/HowMuch.vim 

I HTH

**Comment by sk1418** [comment]
@wcazzola  thanks for reporting this.
I fixed the problem in some awkward way, to check py3 and py2. 
- to make old version vim in old py2 as default system work
- to make HowMuch work under vim8.+ and nvim (nvim doesn't implement pythonx)

please test, hope it works

**Comment by wcazzola** [comment]
Yes, it works. Thank you.
